typography_spectrum: 0.32034
color:
  brandColors:
    - '#a6b3c3'
    - '#5e8cb1'
    - '#9f9996'
    - '#006e8d'
    - '#5a6762'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.92301
analytics:
  google: null
  facebook: null
  twitter: null
name: Right Eye Management
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Right Eye Management
description: Motion Picture and Commercial Crew Management
purpose: []
