name: Right Eye Management
favicon: null
layout_spectrum: 0.87688
typography_spectrum: 0.51369
title: Motion Picture Cast and Crew Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5f5f5f'
    - '#9f9f9f'
    - '#dfdfdf'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
