name: Right Eye Management
favicon: null
layout_spectrum: 0.91373
typography_spectrum: 0.51369
title: Motion Picture Cast and Crew Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f7f7f7'
    - '#713b04'
    - '#b5b5b5'
    - '#ffd908'
  brandStrength: 0.375
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
