name: Right Eye Management
favicon: null
layout_spectrum: 0.91373
typography_spectrum: 0.51369
title: Motion Picture Cast and Crew Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#97cdde'
    - '#3d535a'
    - '#222f33'
    - '#6b939f'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.7656477270647883
  rhythmicContrast: 0.5
purpose: []
